INSERT INTO USERS (NAME, USER_ID) VALUES ('gladky', 1);

INSERT INTO PROJECTS (PROJECT_ID, NAME, HOURS_PER_WEEK, TOTAL_HOURS, PRIORITY, START_DATE, OWNER_ID)
VALUES (1,'NASK', 20, 480, 'a', sysdate-7, 1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (1,1,0,SYSDATE-17,1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (2,1,1,SYSDATE-15,1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (3,1,1,SYSDATE-13,1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (4,1,1,SYSDATE-11,1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (6,1,2,SYSDATE-9,1);

INSERT INTO ENTRIES (ENTRY_ID, PROJECT_ID,AMOUNT,ENTRY_DATE, OWNER_ID)
VALUES (7,1,2,SYSDATE-7,1);